name: terraform

on:
  pull_request:
    paths:
      - "infra/**"
      - ".github/workflows/terraform.yml"

permissions:
  contents: read
  id-token: write

concurrency:
  group: terraform-${{ github.ref }}
  cancel-in-progress: true

jobs:
  aws-auth:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: aws-actions/configure-aws-credentials@e1253824e5c10ff9df46874f81ed3ec929e19cfd # v6.3.0
        with:
          role-to-assume: ${{ vars.AWS_PLAN_ROLE_ARN }}
          aws-region: us-east-1
      - run: aws sts get-caller-identity
